image: registry.gitlab.com/tertsdiepraam/tertsdiepraam.gitlab.io

variables:
  # This variable will ensure that the CI runner pulls in your theme from the submodule
  GIT_SUBMODULE_STRATEGY: recursive

pages:
  script:
    - zola build
    - wkhtmltopdf --page-size A4 -T 30mm -B 30mm -L 30mm -R 30mm --print-media-type ./public/resume-only/index.html resume.pdf
    - mv resume.pdf public/
    
  artifacts:
    paths:
      - public
      
  # This config will only publish changes that are pushed on the master branch
  only:
  - master