image: registry.gitlab.com/tertsdiepraam/tertsdiepraam.gitlab.io

variables:
  # This variable will ensure that the CI runner pulls in your theme from the submodule
  GIT_SUBMODULE_STRATEGY: recursive  
  # Specify the zola version you want to use here
  ZOLA_VERSION: "v0.12.0"

pages:
  script:
    # Download Zola and wkhtmlto
    - curl -L https://github.com/getzola/zola/releases/download/$ZOLA_VERSION/zola-$ZOLA_VERSION-x86_64-unknown-linux-gnu.tar.gz > zola.tar.gz
    - tar -xzf zola.tar.gz
    # Execute zola build
    - bash ./zola build
    # Generate resume HTML
    - wkhtmltopdf ./public/resume_only.html resume.pdf
    - mv resume.pdf public/
    
  artifacts:
    paths:
      # Path of our artifacts
      - public
      
  # This config will only publish changes that are pushed on the master branch
  only:
  - master