# The URL the site will be built for
base_url = "https://tertsdiepraam.gitlab.io/"

title = "Terts Diepraam"

description = "I am Terts, I am developer"

default_language = "en"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

paginate_by = 10

[markdown]
highlight_code = true
highlight_theme = "OneHalfLight"

[extra]
# Put all your custom variables here
author = "Terts Diepraam"
show_author = false
show_categories = false
show_tags = false